name: Kit Test
on:
  push:
    branches: ['dms/bun']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.26

      - name: Kit Install dependencies
        run: |
          bun install
          cd ./framegear && bun install && cd ..

      - name: Kit Test
        # When fails, please check your tests
        run: bun test:coverage